Create 2021-00030 - GitLab Unauthenticated RCE Flaw.md
DIVD-NL/sites pull request #175
Opened 2021-11-19 12:50 UTC by MrIamGr00t

2021-11-24 13:10 UTC, MrSeccubus requested changes

2021-11-24 13:10 UTC, MrSeccubus commented on www.divd.nl/reports/2021-00030 - GitLab Unauthenticated RCE Flaw.md
> +excerpt: We have received a list of GitLab servers running a vulnerable version of GitLab from security researchers at Censys.io. An issue has been discovered in GitLab CE/EE.
```suggestion
excerpt: We have received multiple lists of GitLab servers running a vulnerable version of GitLab from security researchers at Censys.io. An issue has been discovered in GitLab CE/EE. we have notified their administrators.
```

2021-11-24 13:11 UTC, MrSeccubus commented
Also laten we even wachten tot de case gesloten is.

2021-12-02 13:33 UTC, cookiemonster commented
> Ik dacht dat we dit rapport pas gingen publiceren als de case ook gesloten was... ?????

Rapport is ook niet gepubliceerd? Alleen de tekstuele aanpassingen die je hebt aangedragen heb ik goedgekeurd..

2021-12-08 19:33 UTC, MrSeccubus commented
@cookiemonster dit is het PR met het rapport.

2022-02-08 09:08 UTC, wschoot commented
@cookiemonster gevraagd op slack om de status van deze case

2022-02-08 20:37 UTC, merged