Create DIVD-2021-00026.md
DIVD-NL/sites pull request #177
Opened 2021-11-23 22:20 UTC by Lennaert89

add case file.

2021-11-24 08:46 UTC, cookiemonster commented on csirt.divd.nl/cases/DIVD-2021-00026.md
> +- The number of internet facing OMI instances is quite low
internet-facing

2021-11-24 09:14 UTC, cookiemonster commented on csirt.divd.nl/cases/DIVD-2021-00026.md
> +Microsoft’s Open Management Interface (OMI) for Linux servers which is shipped with Azure, LogAnalytics, Microsoft SystemCenter when using it to manage Linux servers, and potentially more software an
quite --> relatively

2021-11-24 09:15 UTC, cookiemonster commented on csirt.divd.nl/cases/DIVD-2021-00026.md
> +We have discussed and confirmed these conclusions with the researchers from Wiz, nonetheless, we still think that OMIGOD is a significant security risk. It offers attackers substantial opportunity to
from Wiz; nonetheless,

2021-11-24 09:17 UTC, cookiemonster commented on csirt.divd.nl/cases/DIVD-2021-00026.md
> +We have discussed and confirmed these conclusions with the researchers from Wiz, nonetheless, we still think that OMIGOD is a significant security risk. It offers attackers substantial opportunity to
Also, companies

2021-11-24 13:07 UTC, MrSeccubus requested changes

2021-11-24 13:07 UTC, MrSeccubus commented on csirt.divd.nl/cases/DIVD-2021-00026.md
> +We recommend you to update your Linux servers running Microsoft Open Management Interface (OMI) to version 1.13.40-0 or later as the specific vulnerability was patched in this version.
```suggestion
We recommend you to update your Linux servers running Microsoft Open Management Interface (OMI) to version 1.13.40-0 or later as the specific vulnerability was patched in this version, additionally we recommend that you disable the OMI service if you yourself are not actively using it.
```

2021-11-24 13:07 UTC, MrSeccubus commented on csirt.divd.nl/cases/DIVD-2021-00026.md
> +- The number of internet facing OMI instances is quite low
```suggestion
- The number of internet-facing OMI instances is quite low
```

2021-11-24 13:07 UTC, MrSeccubus commented on csirt.divd.nl/cases/DIVD-2021-00026.md
> +We have discussed and confirmed these conclusions with the researchers from Wiz, nonetheless, we still think that OMIGOD is a significant security risk. It offers attackers substantial opportunity to
```suggestion
We have discussed and confirmed these conclusions with the researchers from Wiz; nonetheless, we still think that OMIGOD is a significant security risk. It offers attackers substantial opportunity to move laterally and escalate privileges once they have compromised a host in the network. Also, companies may be running this service without their explicit knowledge, because it’s installed by default when using certain Azure services even on hosts not running inside the Azure cloud platform. Though, due to the limited internet exposure of OMI servers, we cannot work on this case any longer.
```

2021-11-24 13:07 UTC, MrSeccubus commented on csirt.divd.nl/cases/DIVD-2021-00026.md
> +| 8 Nov 2021 | Casefile written and case closed |
```suggestion
| 24 Nov 2021 | Casefile written and case closed |
```

2021-11-26 09:12 UTC, therealprocyon approved these changes

2021-11-26 09:14 UTC, therealprocyon submitted a review, later dismissed

2021-12-02 17:50 UTC, wschoot approved these changes

2021-12-02 17:50 UTC, wschoot commented on csirt.divd.nl/cases/DIVD-2021-00026.md
> +short: Omigod: vulnerabilities make it possible to execute remote code via Microsoft Open Management Interface (OMI) this service is installed automatically on machines running certain Azure services
```suggestion
short: Omigod vulnerabilities make it possible to execute remote code via Microsoft Open Management Interface (OMI) this service is installed automatically on machines running certain Azure services (either on premise or in the cloud)
```

Gebruik van de ":" zorgt ervoor dat de titel niet goed gerenderd wordt maar er enkel "Summary" staat in 't menu:
![image](https://user-images.githubusercontent.com/3919193/144475542-7d66458e-d1ba-4f5a-a9f4-dcc0b039cbdf.png)

Geeft de volgende melding in de logs:
> YAML Exception reading /root/project/csirt.divd.nl/cases/DIVD-2021-00026.md: (<unknown>): mapping values are not allowed in this context at line 5 column 14

2021-12-02 17:50 UTC, wschoot commented on csirt.divd.nl/cases/DIVD-2021-00026.md
> +title: DIVD-2021-00026 - Omigod: Microsoft Open Management Interface RCE
```suggestion
title: "DIVD-2021-00026 - Omigod: Microsoft Open Management Interface RCE"
```
Fixes:
> YAML Exception reading /root/project/csirt.divd.nl/cases/DIVD-2021-00026.md: (<unknown>): mapping values are not allowed in this context at line 3 column 32

2021-12-02 18:00 UTC, merged