Initial case file for subdomain takeovers
DIVD-NL/sites pull request #287
Opened 2022-02-11 11:42 UTC by martinvw

2022-02-11 11:50 UTC, wschoot commented on csirt.divd.nl/_cases/DIVD-2022-00007.md
> +Subdomain takeovers do not only, allow the attacker to publish content on the targets website, but in some case it will also allow reading (session) cookies, perform other attacks such as cross-site
```suggestion
Subdomain takeovers do not only allow the attacker to publish content on the targets website, but in some case it will also allow reading (session) cookies, perform other attacks such as cross-site scripting or even trick password managers.
```

2022-02-11 11:54 UTC, wschoot submitted a review, later dismissed
Goed bezig, mooie caseomschrijving! Paar kleine tekstuele dingen die ik persoonlijk net wat anders zou schrijven. Hoe sta jij hierin @martinvw ?

2022-02-11 11:54 UTC, wschoot commented on csirt.divd.nl/_cases/DIVD-2022-00007.md
> +Since 2014 subdomain takeovers have been growing problem. Thanks to the increased adoption of cloud this is also not a problem that will go away easily.
```suggestion
Since 2014 subdomain takeovers have been growing problem. Due to the increased adoption of cloud this is also not a problem that will go away easily. 
```

Vind ik iets mooier dan de licht-cynische "Thanks to" :-)

2022-02-11 11:54 UTC, wschoot commented on csirt.divd.nl/_cases/DIVD-2022-00007.md
> +Most other services provide not additional security measure, if the service is completely removed from Azure while the CNAME is still there, subdomain takeover are possible.
```suggestion
Most other services don't provide additional security measure. If the service is completely removed from Azure while the CNAME is still there, subdomain takeover are possible.
```

2022-02-11 12:05 UTC, Lennaert89 requested changes

2022-02-11 12:05 UTC, Lennaert89 commented on csirt.divd.nl/_cases/DIVD-2022-00007.md
> +  event: "First DiVD scan of CNAMES of .NL domains pointing to unregistered domains"
Capitalize the I

2022-02-11 12:05 UTC, Lennaert89 commented on csirt.divd.nl/_cases/DIVD-2022-00007.md
> +  event: DIVD sent out a first batch of notifications
DIVD shares first batch of NL space notifications with our Trusted Information Sharing Partner Digital Trust Center so they can inform vulnerable parties.

2022-02-13 09:35 UTC, wschoot approved these changes

2022-02-13 09:36 UTC, merged