Add files via upload
DIVD-NL/sites pull request #363
Opened 2022-04-02 11:18 UTC by Maximand

2022-04-02 11:24 UTC, xstp commented on csirt.divd.nl/_cases/DIVD-2022-00023.md
> +title: DIVD-2022-00023 - Spring Core RCE Zeroday
Maybe replace Zeroday with CVE-2022-22965

2022-04-02 11:34 UTC, xstp commented on csirt.divd.nl/_cases/DIVD-2022-00023.md
> +- CVE-2022-22963
Wrong CVE (this is the Spring Cloud one). Core is CVE-2022-22965

2022-04-02 17:19 UTC, MrSeccubus requested changes

2022-04-02 17:19 UTC, MrSeccubus commented on csirt.divd.nl/_cases/DIVD-2022-00023.md
> +title: DIVD-2022-00023 - Spring Core RCE Zeroday
```suggestion
title: DIVD-2022-00023 - Spring Core RCE Zeroday (CVE-2022-22965)
```

2022-04-02 17:19 UTC, MrSeccubus commented on csirt.divd.nl/_cases/DIVD-2022-00023.md
> +redirect_from:
Dit is niet meer nodig tegenwoordig.

2022-04-02 17:19 UTC, MrSeccubus commented on csirt.divd.nl/_cases/DIVD-2022-00023.md
> +- CVE-2022-22963
```suggestion
- CVE-2022-22965
```

2022-04-02 17:19 UTC, MrSeccubus commented on csirt.divd.nl/_cases/DIVD-2022-00023.md
> +-workaround: Downgrading to JDK 8.
```suggestion
workaround: Downgrading to JDK 8.
```
Minnetje moet weg anders laat hij hem niet zien.

2022-04-04 09:35 UTC, Lennaert89 approved these changes

2022-05-25 12:12 UTC, closed without merging