add draft for casefile 00027
DIVD-NL/sites pull request #381
Opened 2022-05-10 10:20 UTC by xstp

@Ralphhorn

2022-05-10 10:43 UTC, Maximand requested changes

2022-05-10 10:43 UTC, Maximand commented on csirt.divd.nl/_cases/DIVD-2022-00027.md
> +By leveraging the ulnerability, an unauthenticated attacker with network access to the BIG-IP system through the management port and/or self IP addresses to execute arbitrary system commands, create
Typo: vulnerability

2022-05-10 10:43 UTC, Maximand commented on csirt.divd.nl/_cases/DIVD-2022-00027.md
> +* We validate the vulnerability by executing a non-existant command and match the response.
Typo: non-existent

2022-05-11 08:24 UTC, wschoot approved these changes

2022-05-11 08:24 UTC, merged