Create security.txt
DIVD-NL/sites pull request #382
Opened 2022-05-11 14:41 UTC by vcartman

Created security.txt with the links to the Vulnerability Disclosure Program.

2022-05-19 20:29 UTC, glangendam commented
Attached is a security.txt file that is more in line with RFC 9116. It should be located at divd.nl/.well-known/security.txt

[security.txt](https://github.com/DIVD-NL/sites/files/8734031/security.txt)

2022-05-20 09:40 UTC, MrSeccubus requested changes
Suggestion, lets make this more in line with the RFC.

It should be located in the .well-known directory too and be present on www as well.

2022-05-20 09:40 UTC, MrSeccubus commented on csirt.divd.nl/_cases/DIVD-2022-00025.md
> +  event: Second batch of notifications sent
Don;t this is this an update of security.txt.

2022-05-24 19:56 UTC, cookiemonster commented
We have a VDP btw. 
https://www.divd.nl/security/

2022-05-25 09:08 UTC, glangendam commented
> @glangendam we deliberately chose the bug bounty progrtam ursl over email. ((And if ywe accept email I would either suggest question@ or csirt@ rather then security@)
 
I added the email because 'some' organizations use automated scanning and emailing of vulnerabilities. They benefit hugely from a standardized location of an email address. I think DIVD should give a good example, maybe?

> Also a number of URL's that you mention in the attachment are not actually working.
My apologies, it was more a suggestion how a security.txt should look according to RFC9116.

> @vcartman / @glangendam who is going to incoraporate these suggetions into the PR?
I have not much experience in this, but I would be happy to.

2022-06-01 12:08 UTC, closed without merging